apiVersion: apps/v1
kind: Deployment
metadata:
  name: geotransform
  labels:
    apps: geotransform
spec:
  selector:
    matchLabels:
      app: geotransform
  template:
    metadata:
      labels:
        app: geotransform
    spec:
      containers:
      - name: geotransform
        image: hub.adaspace.org.cn/ai/geometric_position:py3.12-gdal3.10-v1.0
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     cpu: 200m
        #     memory: 512Mi
        ports:
        - containerPort: 9876
        envFrom:
          - configMapRef:
              name: geotransform-config


---
apiVersion: v1
kind: Service
metadata:
  name: geotransform
  labels:
    app: geotransform
spec:
  selector:
    app: geotransform
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9876


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: geotransform
spec:
  routes:
  - kind: Rule
    match: Host(`geotransform.test`) && PathPrefix(`/`)
    services:
    - name: geotransform
      port: 80


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geotransformo-config
data:
  GUNICORN_THREADS: "8"
  DEBUG: "1"
  ALLOWED_HOSTS: "*"
  REDIS_HOST: "redis"
  REDIS_DB: "1"
  SWAGGER_ENABLED: "1"
